app_version: 0.18.0
capabilities: []
categories:
- management
date_added: '2025-04-14'
description: Homebox is the inventory and organization system built for the Home User!
  With a focus on simplicity and ease of use, Homebox is the perfect solution for
  your home inventory, organization, and management needs.
home: https://github.com/sysadminsmedia/homebox
host_mounts: []
icon: https://media.sys.truenas.net/apps/homebox/icons/icon.png
keywords:
- inventory
- organization
- management
lib_version: 2.1.18
lib_version_hash: 012ae94d28ee9d63c3c51a531bf5ac943e585015d5bcb1a6b20210b90d17dece
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: homebox
run_as_context:
- description: Homebox runs as any non-root user.
  gid: 568
  group_name: homebox
  uid: 568
  user_name: homebox
screenshots:
- https://media.sys.truenas.net/apps/homebox/screenshots/screenshot1.png
sources:
- https://github.com/sysadminsmedia/homebox
title: Homebox
train: community
version: 1.0.0
