{% set tpl = ix_lib.base.render.Render(values) %}

{% set server = tpl.add_container(values.consts.homebox_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% do server.set_user(values.run_as.user, values.run_as.group) %}
{% do server.healthcheck.set_test("wget", {"port": values.consts.internal_server_port, "path": "/favicon.ico"}) %}
{% do server.remove_devices() %}

{% do server.environment.add_env("NODE_ENV", "production") %}
{% do server.environment.add_env("DATA_PATH", values.consts.data_path) %}
{% do server.environment.add_user_envs(values.handbrake.additional_envs) %}
{% do server.add_port(values.network.web_port, {"container_port": values.consts.internal_server_port}) %}

{% do server.add_storage(values.consts.data_path, values.storage.data) %}
{% do perm_container.add_or_skip_action("data", values.storage.data, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do server.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do server.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add_portal({"port": values.network.web_port.port_number}) %}

{{ tpl.render() | tojson }}
